import type { Metadata } from "next";
import { aclonica } from '@/app/ui/fonts';
import "./globals.css";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${aclonica.className} antialiased bg-cover bg-no-repeat bg-center bg-my_bg_image_mobile md:bg-my_bg_image h-fit bg-fixed`}>
        <div>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
